### ISSUE TITLE
Overlay information on F2P Accounts is drawn offset due to advertisement

### ISSUE THREAD

**Issue by Danlowe95** [powerbot/powerbot#966] opened 2015-10-01 20:59 UTC
All overlay drawings (mouse, object ids, gameobject ids, etc) are being drawn about an inch higher than their actual location, because the advertisement for Runescape inside the client is offsetting all drawing.  I'd recommend a check to see if advertisement is displayed, and if so, offset all drawing by advertisement-height.

**Comment by Timer** [comment] 2015-10-01 23:49
Duplicate of #935.

**Closed by Timer** 2015-10-01 23:49 UTC
Labels: bug, duplicate, gui
