### ISSUE TITLE
Trading inventory

### ISSUE THREAD

**Issue by MaartenBoodts** [powerbot/powerbot#1414] opened 2016-04-28 17:15 UTC
When the trading window is open, inventory returns false to valid.

widget component trading screen 1 (where you put the items in and accept for the first time): 335
widget component trading screen  (where you accept for the second time): 334

**Comment by stumpy3toes** [comment] 2016-04-29 10:51
The problem is that widget 149 is not visible during the first trade screen because it has it's own widget inventory 336. During the second trade screen widget 336 is no longer valid and 149 is visible again

**Comment by ChrisBPB** [comment] 2016-04-29 12:27
so 336 needs adding ^.^

**Comment by Moosheplusplus** [comment] 2016-04-29 23:34
That's because the second screen (widget index 336) is not an inventory (an indication that there's an array of item IDs in the widget). The second trading screen window is just a list of item names and quantities, and does not store any item IDs.

**Comment by ChrisBPB** [comment] 2016-04-30 09:49
@Moosheplusplus think the wording has confused you, 336 isn't the second screen - 334 is

336 is just another inventory that is present during the first trade screen - then on the 2nd trade screen 149 is visible again

http://i.imgur.com/GmovCRq.png

**Comment by ChrisBPB** [comment] 2016-04-30 09:51
ref https://github.com/powerbot/powerbot/issues/817

**Comment by stumpy3toes** [comment] 2016-04-30 11:27
Yeah my bad with the wording.
First trade screen interface widget id: 335
Second trade screen interface widget id: 334
During the first trade screen the inventory widget id: 336

**Comment by Moosheplusplus** [comment] 2017-01-14 02:25
This was fixed in #1459. Double-checked and made sure it worked; it does. Please close this @Timer or @Paris

**Comment by Moosheplusplus** [comment] 2017-04-30 21:25
@Strikegently this was fixed.

**Closed** 2017-05-09 08:20 UTC
Labels: api, bug, rt4
