### ISSUE TITLE
Linux Overlay OpenJDK

### ISSUE THREAD

**Issue by Echocage** [powerbot/powerbot#1036] opened 2015-10-29 10:48 UTC
OS: Arch
Java: OpenJDK 1.7.0_85

![Image of bug](http://i.imgur.com/z0E2KRv.jpg)

Steps

* Start bot

All overlay graphics flicker constantly and won't disappear until you resize the client. This happens with everything in the view menu, but is especially annoying because the trail from the mouse never goes away and blocks the screen after a very short amount of time, even with mouse trail off

Probably just a oddity with the OpenJDK implementation

**Comment by Paris** [comment] 2015-10-29 12:41
Duplicate of #778

**Closed by Paris** 2015-10-29 12:41 UTC
