### ISSUE TITLE
Script selection window sometimes hangs

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#951] opened 2015-09-28 11:45 UTC
The window where you select which script to run sometimes becomes non-responsive. The game is still running normally, but you can't do anything to close this window. The only way to solve this right now is to reload the client. No errors are thrown when this happens.

**Comment by Paris** [comment] 2015-10-11 12:09
Does this still happen? Do you know how to reproduce it or is it random?

**Comment by ArtificialPB** [comment] 2015-10-11 12:30
Yes it still happens. I've noticed it usually occurs if you minimize rsbot while script selection is loading.

**Comment by ArtificialPB** [comment] 2015-10-27 10:01
If it helps you in any way, I'm using 64x Windows 10 Pro  (Version: 10.0.10240 Build 10240).

**Comment by Paris** [comment] 2015-11-08 14:33
Closing due to lack of information, if you have any more details please update.

**Closed by Paris** 2015-11-08 14:33 UTC
Labels: bug, gui

**Comment by ArtificialPB** [comment] 2015-11-09 21:53
Just found out it happens if the rsbot is not focused when it's loading. Not only when the client is minimized.

**Comment by Timer** [comment] 2015-11-11 00:56
Can you reproduce it @ArtificialPB ?

**Comment by ArtificialPB** [comment] 2015-11-11 17:03
Probably. The thing is that it does not happen always. You can teamview me if you'd like @Timer and I'll try to reproduce it.
